disabled_rules:
 - trailing_whitespace
 - vertical_parameter_alignment
 - identifier_name

excluded:
  - Example/

force_try: warning
force_cast: warning
type_body_length:
- 300 # warning
- 400 # error
line_length: 140
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 140
    error: 140
colon:
  apply_to_dictionaries: false
variable_name:
  excluded:
    - id
statement_position:
   statement_mode: uncuddled_else
